# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1330, 914)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(1250, 840, 81, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(70)
        self.sendButton.setFont(font)
        self.sendButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("32213.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendButton.setIcon(icon)
        self.sendButton.setIconSize(QtCore.QSize(64, 64))
        self.sendButton.setObjectName("sendButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 840, 1251, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setObjectName("textEdit")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1331, 841))
        self.tabWidget.setObjectName("tabWidget")
        self.chat_tab = QtWidgets.QWidget()
        self.chat_tab.setObjectName("chat_tab")
        self.listWidget = QtWidgets.QListWidget(self.chat_tab)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 1331, 811))
        self.listWidget.setObjectName("listWidget")
        self.tabWidget.addTab(self.chat_tab, "")
        self.account_tab = QtWidgets.QWidget()
        self.account_tab.setObjectName("account_tab")
        self.nameEdit = QtWidgets.QLineEdit(self.account_tab)
        self.nameEdit.setGeometry(QtCore.QRect(120, 40, 361, 41))
        self.nameEdit.setObjectName("nameEdit")
        self.nameLabel = QtWidgets.QLabel(self.account_tab)
        self.nameLabel.setGeometry(QtCore.QRect(10, 50, 101, 21))
        self.nameLabel.setObjectName("nameLabel")
        self.usernameLabel = QtWidgets.QLabel(self.account_tab)
        self.usernameLabel.setGeometry(QtCore.QRect(10, 100, 101, 21))
        self.usernameLabel.setObjectName("usernameLabel")
        self.usernameEdit = QtWidgets.QLineEdit(self.account_tab)
        self.usernameEdit.setGeometry(QtCore.QRect(120, 90, 361, 41))
        self.usernameEdit.setObjectName("usernameEdit")
        self.passwordEdit = QtWidgets.QLineEdit(self.account_tab)
        self.passwordEdit.setGeometry(QtCore.QRect(120, 140, 361, 41))
        self.passwordEdit.setObjectName("passwordEdit")
        self.passwordLabel = QtWidgets.QLabel(self.account_tab)
        self.passwordLabel.setGeometry(QtCore.QRect(10, 150, 101, 21))
        self.passwordLabel.setObjectName("passwordLabel")
        self.tabWidget.addTab(self.account_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionAccount = QtWidgets.QAction(MainWindow)
        self.actionAccount.setCheckable(False)
        self.actionAccount.setObjectName("actionAccount")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Type anything..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chat_tab), _translate("MainWindow", "Chat"))
        self.nameLabel.setText(_translate("MainWindow", "Name"))
        self.usernameLabel.setText(_translate("MainWindow", "Username"))
        self.passwordLabel.setText(_translate("MainWindow", "Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.account_tab), _translate("MainWindow", "Account"))
        self.actionAccount.setText(_translate("MainWindow", "Account"))
